// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("backend.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedBuddy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnsiteDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Engineering",
                            FullName = "Alex Popescu",
                            Role = "Junior Developer"
                        },
                        new
                        {
                            Id = 2,
                            Department = "HR",
                            FullName = "Maria Ionescu",
                            Role = "HR Specialist"
                        });
                });

            modelBuilder.Entity("backend.Models.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OnboardingTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Join the #general channel.",
                            EmployeeId = 1,
                            IsCompleted = false,
                            Title = "Set up Slack account"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Schedule a 15-minute meeting on Google Meet.",
                            EmployeeId = 1,
                            IsCompleted = false,
                            Title = "Meet the Manager"
                        });
                });

            modelBuilder.Entity("backend.Models.OnboardingTask", b =>
                {
                    b.HasOne("backend.Models.Employee", "Employee")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("backend.Models.Employee", b =>
                {
                    b.Navigation("OnboardingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
